// Generated by https://quicktype.io

export interface GetFamilyResponse {
  data: Datum[];
  responseStatus: ResponseStatus;
}

export interface Datum {
  firstName: string;
  lastName: string;
  dob: string;
  isDelegate: boolean;
  isDelegateEligible: boolean;
  isRegistered: boolean;
  relationshipcode: string;
  isAgeEligible: boolean;
  isRegistrationEligible: boolean;
  invitationStatus: string;
  inviteeEmail: string;
  hasActiveCoverage: boolean;
  uniqueId: string;
}

export interface ResponseStatus {
  status: number;
  responseCode: string;
}
